# -*- coding: utf-8 -*-
"""213902037_Class_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1430Fx6nEgB_JaSTYWisZkIZjGxk5qNnu
"""

sum = 0
i = 1
while i <= 50:
    sum = sum + i
    i = i + 1
print(sum)







n = int(input("Enter a number: "))
i = 0
while i <= 10 :
    print(n, "x", i , "=" , n * i)
    i = i + 1
    sum = sum + 1
    print(sum)

n = int(input("Enter a number: "))
sum = 0
while n > 0 :
  d = n % 10
  n = n // 10
  sum = sum + d



n = int(input("Enter a number: "))
sum = 0
while n > 0 :
  d = n % 10
  n = n // 10
  sum = sum + d

print(sum)



sum = 0
i = 15
while i <= 30:
    sum = sum + i
    i = i + 1
print(sum)

sum = 0
i = 1
while i <= 30:
    sum = sum + i
    i = i + 1
print(sum)

n = int(input("Enter a number: "))
sum = n * (n + 1) // 2
print("Sum of first", n, "natural numbers is:", sum)

sum = 0
i = 1
while i <= 20:
    if i % 2 == 0:
        sum += i
    i += 1
print(sum)

sum = 0
i = 2
while i <= 20:
    print (i)
    i += 2

Fact = 1
i = 1
while i <= 20:
    if i % 2 == 0:
        fact *= i
    i += 1
print(fact)



fact = 1
i = 1
while i <= 20:
    if i % 2 == 0:
        fact *= i
    i += 1
print(fact)

"""Sum Of Natrual Number

"""

A = [36, 69, 24, 32 , 45]
print (A)
print (A[2])
A[3] = A [2]
print (A)
A[1] += 10
print (A)



A = [36, 69, 24, 32, 45, 62, 45, 93]
print( A)
i = 0
while i < len(A) / 2:
    A[i], A[len(A) - i - 1] = A[len(A) - i - 1], A[i]
    i += 1
print( A)

A = [36, 69, 24, 32, 45, 62, 45, 93]
max_val = A[0]
max_index = 0

i = 0
while i < len(A):
    if A[i] > max_val:
        max_val = A[i]
        max_index = i
    i += 1

print("Maximum value:", max_val)
print("Index of maximum value:", max_index)

A = [36, 69, 24, 32, -45, 62, 45, 93]
i = 0
while i < len(A):
    if A[i] < 0:
        break
    else:
        print(A[i])
    i += 1

i = 1
while i<=20:
if i % 2 == 0:
   print(A)

# prompt: attempt = 3

attempt = 3
sum = 0
i = 1
while i <= 50:
    sum = sum + i
    i = i + 1
print(sum)

n = int(input("Enter a number: "))
i = 0
while i <= 10 :
    print(n, "x", i , "=" , n * i)
    i = i + 1
    sum = sum + 1
    print(sum)

n = int(input("Enter a number: "))
sum = 0
while n > 0 :
  d = n % 10
  n = n // 10
  sum = sum + d

n = int(input("Enter a number: "))
sum = 0
while n > 0 :
  d = n % 10
  n = n // 10
  sum = sum + d

print(sum)

sum = 0
i = 15
while i <= 30:
    sum = sum + i
    i = i + 1
print(sum)
sum = 0
i = 1
while i <= 30:
    sum = sum + i
    i = i + 1
print(sum)
n = int(input("Enter a number: "))
sum = n * (n + 1) // 2
print("Sum of first", n, "natural numbers is:", sum)

sum = 0
i = 1
while i <= 20:
    if i % 2 == 0:
        sum += i
    i += 1
print(sum)

sum = 0
i = 2
while i <= 20:
    print (i)
    i += 2

Fact = 1
i = 1
while i <= 20:
    if i % 2 == 0:
        Fact *= i
    i += 1
print(Fact)
fact = 1
i = 1
while i <= 20:
    if i % 2 == 0:
        fact *= i
    i += 1
print(fact)
#
# Sum Of Natrual Number
#
A = [36, 69, 24, 32 , 45]
print (A)
print (A[2])
A[3] = A [2]
print (A)
A[1] += 10
print (A)
A = [36, 69, 24, 32, 45, 62, 45, 93]
print( A)
i = 0
while i < len(A) / 2:
    A[i], A[len(A) - i - 1] = A[len(A) - i - 1], A[i]
    i += 1
print( A)



A = [36, 69, 24, 32, 45, 62, 45, 93]
max_val = A[0]
max_index = 0

i = 0
while i < len(A):
    if A[i] > max_val:
        max_val = A[i]
        max_index = i
    i += 1

print("Maximum value:", max_val)
print("Index of maximum value:", max_index)

A = [36, 69, 24, 32, -45, 62, 45, 93]
i = 0
while i < len(A):
    if A[i] < 0:
        break
    else:
        print(A[i])
    i += 1

i = 1
while i<=20:
  if i % 2 == 0:
     print(A)
  i += 1

attempt = 3
pass_="abc123"
password = input("Enter password: ")
i = 0
while  i< attempt:
  if password == pass_:
    break
  i += 1

if match:

    print ("Access Granted")
  else:
    print ("Access denied")