# -*- coding: utf-8 -*-
"""213902037_Class_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwMMV7XVREEE33V09A1JNVllJkPqOxoP
"""

language = ['Python', 'C++', 'JavaScript', 'C', 'Java', 'HTML']
print(language)
print(language[3])
print(language[-2])
for i in language:
     print(i)

language = ['Python', 'C++', 'JavaScript', 'C', 'Java', 'HTML']
print(language)
print(language[3])
print(language[-2])
for i in language:
    if i.startswith ('c'):
         print(i)

language = ['Python', 'C++', 'JavaScript', 'C', 'Java', 'HTML']
language[0] = 'C#'
print(language)

NameList = list()
for i in range (5):
        name = input(f"Enter student name {i+1}: ")
        NameList.append(name)
        print(NameList)
        for name in NameList:
            print(name.upper())

numbers = []
for i in range(10):
  num = int(input("Enter a number: "))
  numbers.append(num)

print("Odd numbers in the list:")
for num in numbers:
  if num % 2 != 0:
   num(print)

numbers = []
for i in range(10):
  num = int(input("Enter a number:"))
  numbers.append(num)
print("Odd numbers in the list:")
for num in numbers:
  if num % 2 != 0:
    print(num)

NL = [23,45,67,66,92, 34, 69]
def isOdd (n):
    if n % 2 == 1:
        return True
    else:
        return False
odd_numbers = list(map(isOdd, NL))
print(odd_numbers)

NL = [23,45,67,66,92, 34, 69]
def isOdd (n):
    if n % 2 == 1:
        return True
    else:
        return False
odd_numbers = list(map(isOdd, NL))
print(odd_numbers)

NL = [23,45, 67,66,92,34, 69]

...
for num in NL:
    if num % 2 != 0:
        print(num)

# Get 5 words from the user and store them in a list
words = []
for i in range(5):
  word = input("Enter a word: ")
  words.append(word)

# Iterate through the list and display words starting with "b"
print("Words starting with 'b':")
for word in words:
  if word.startswith("b"):
    print(word)

lst = list(range (50))
print(lst)
nwlst = [x+1 for x in lst]
print(nwlst)

Colors = ['Yellow', 'pink', 'gray', 'white','black']
nwclr =[color for color in Colors if 'a' in color]
print(nwclr)

dir (list)

my_list = []
for _ in range (5):
    item = input("Enter an item: ")
    my_list.append(item)
print("Original list:",my_list)

if my_list:
    del my_list[0]
    print("List after removing the first:",my_list)
else:
        print("List is empty")

numbers = []
for _ in range(5):
  num = int(input("Enter an integer:"))
  numbers.append(num)
for num in numbers:
  print(f"Number: {num},Square: {num**2}")

numbers = [4,6,7,9,2]
new_nl =[x * x for x in numbers]
print (new_nl)
new_nl = map (lambda x: x * x,numbers)

numbers = [2,3,4,5,6]
numbers.remove(3)
print(numbers)

my_list = ['apple', 'banana', 'cherry', 'date']
print("Original list:", my_list)

try:
    index = int(input("Index to modify: "))
    if 0 <= index < len(my_list):
        my_list[index] = input("New value: ")
        print("Modified list:", my_list)
    else:
        print("Invalid index.")
except ValueError:
    print("Invalid input.")