# -*- coding: utf-8 -*-
"""213902037_Rabby_Class_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-pY4rusQ_Qi5ISih16KV4QHuc7KbZy1F
"""

print (123)
print(" Hello!")



x = 12.2
y = 14
print(x)
print(x,y)
print('x:', x,'y:',y)
print ('x,: '+str(x)+'y:'+ str(y))

pi= 3.14
r = 3
area = pi*r**2
print(area)



a = 10
b = 20
a= a+b
b = a-b
a = a-b
print(a,b)

P = 100
R = 5
T = 2
SI = (P*R*T)/100
print(SI)

celsius = 37
fahrenheit = (celsius * 9/5) + 32
print(fahrenheit)

print(type (12.3))
print(type("sdfsdf"))
print(type(12))

noun = 'David'
day = 'Monday'

str_ = f'''How are you Mr. {noun}. You are invited to come my home on{day}.
{noun} don't miss the chance'''
print(str_)

hours = float(input("Enter Hours: "))
rate = float(input("Enter Rate: "))

pay = hours * rate

# Print the result
print(f"Pay: {pay}")

#print(n = 7)

print(7 + 5)  # Output: 12

print(5.2, "this", 4 - 2, "that", 5 / 2.0)

w1 = "All"
w2 = "work"
w3 = "and"
w4 = "no"
w5 = "play"
w6 = "makes"
w7 = "Jack"
w8 = "a"
w9 = "dull"
w10 = "boy."

# Print the sentence on one line
print(w1, w2, w3, w4, w5, w6, w7, w8, w9, w10)

# print("This line is commented out.")
print("This line will print.")

6 * 1 - 2  # Evaluates to 4

6 * (1 - 2)  # Evaluates to -6

bruce = 6
print(bruce + 4)  # Output: 10

noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
adjective = input("Enter an adjective: ")
adverb = input("Enter an adverb: ")
plural_noun = input("Enter a plural noun: ")
past_verb = input("Enter a past tense verb: ")


madlib = f"""
Today I saw a {adjective} {noun} at the park. It decided to {verb} {adverb}
in front of a group of {plural_noun}. Everyone was shocked, and one person even
{past_verb} in surprise! What a strange day!"""

print("\n--- Here is your Mad Lib! ---")
print(madlib)

import random
nouns = ["cat", "dog", "alien", "pizza", "robot"]
verbs = ["run", "dance", "jump", "sing", "fly"]
adjectives = ["purple", "smelly", "gigantic", "angry", "tiny"]
adverbs = ["quickly", "happily", "awkwardly", "loudly", "gracefully"]
plural_nouns = ["penguins", "zombies", "children", "cars", "bicycles"]
past_verbs = ["screamed", "laughed", "fainted", "cried", "cheered"]

noun = random.choice(nouns)
verb = random.choice(verbs)
adjective = random.choice(adjectives)
adverb = random.choice(adverbs)
plural_noun = random.choice(plural_nouns)
past_verb = random.choice(past_verbs)


madlib = f"""
Today I saw a {adjective} {noun} at the park. It decided to {verb} {adverb}
in front of a group of {plural_noun}. Everyone was shocked, and one person even
{past_verb} in surprise! What a strange day!"""

print("\n--- Here is your Random Mad Lib! ---")
print(madlib)

